spring:
  application:
    name: springboot-kafka
  # kafka 连接地址
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    # 生产者
    producer:
      # value的序列化器 默认是 StringSerializer.class
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      # key的序列化器
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 配置轮询分区器
      properties:
        partitioner:
          class: org.apache.kafka.clients.producer.RoundRobinPartitioner
    # 消费者
    consumer:
      # 将偏移量设置到最早  读取历史消息
      auto-offset-reset: earliest
    # 设置默认主题
    template:
      default-topic: default-topic


